apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-k8s-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aws-k8s-app
  template:
    metadata:
      labels:
        app: aws-k8s-app
    spec:
      containers:
        - name: aws-k8s-app
          image: 679346886253.dkr.ecr.us-east-1.amazonaws.com/aws-k8s-app:0b7e87e360f4b93f098721f8b35e459a7e7c7795
          ports:
            - containerPort: 8000
          env:
            - name: APP_VERSION
              value: "v1"